<?php
// $Id$

/**
 * @file
 * Enables voting on polls without reloading the page.
 */

/**
 * Implements hook_menu().
 */
function ajax_poll_menu() {
  return array(
    'poll/ajax/vote/%/%' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'ajax_poll_callback',
      'page arguments' => array(2, 3, 4),
      'access arguments' => array('vote on polls'),
    ),
    'poll/ajax/cancel/%/%' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'ajax_poll_callback',
      'page arguments' => array(2, 3, 4),
      'access arguments' => array('cancel own vote'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function ajax_poll_init() {
  // It would be ideal to not load this JavaScript on every page. However since
  // block caching will not add the necessary files if block caching is enabled,
  // we have to add these files on every page.
  if (variable_get('block_cache', 0)) {
    drupal_add_js('misc/jquery.form.js');
    drupal_add_js(drupal_get_path('module', 'ajax_poll') . '/ajax_poll.js');
  }
}

/**
 * Implements hook_form_alter().
 */
function ajax_poll_form_alter(&$form, $form_state, $form_id) {
  if (in_array($form_id, array('poll_view_voting', 'poll_cancel_form'))) {
    drupal_add_js('misc/jquery.form.js');
    drupal_add_js(drupal_get_path('module', 'ajax_poll') . '/ajax_poll.js');

    $node = isset($form['#node']) ? $form['#node'] : node_load($form['#nid']);

    $teaser = (int) isset($node->teaser);
    $block = (int) !empty($form['#block']);
    $action = ($form_id == 'poll_view_voting') ? 'vote' : 'cancel';

    $form['ajax_url'] = array(
      '#type' => 'hidden',
      '#value' => url('poll/ajax/' . $action . '/' . $teaser . '/' . $block),
    );
    $form['ajax_text'] = array(
      '#type' => 'hidden',
      '#value' => ($action == 'vote') ? t('Voting...') : t('Canceling...'),
    );

    // Add the AJAX Poll class to the form.
    if (empty($form['#attributes']['class'])) {
      $form['#attributes']['class'] = 'ajax-poll';
    }
    else {
      $form['#attributes']['class'] .= ' ajax-poll';
    }
    $form['#attributes']['class'] .= ' ajax-' . $action;
  }
}

/**
 * Menu callback for poll/ajax.
 */
function ajax_poll_callback($type, $teaser, $block) {
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);

  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  $form['#programmed'] = $form['#redirect'] = FALSE;

  drupal_process_form($form_id, $form, $form_state);

  $nid = isset($form['#nid']) ? $form['#nid'] : $form['#node']->nid;
  $node = node_load(array('nid' => $nid));
  $poll = poll_view($node, $teaser, FALSE, $block);
  $status = count(drupal_get_messages('error', FALSE)) == 0;
  $messages = theme('status_messages');
  $output = drupal_render($poll->content);

  drupal_json(array('status' => $status, 'messages' => $messages, 'output' => $output));
}
